<?php

namespace Database\Seeders;

use App\Models\Asset;
use App\Models\Location;
use Illuminate\Database\Seeder;

class AssetSeeder extends Seeder
{
    public function run(): void
    {
        $loc = Location::all()->keyBy('code');

        $assets = [
            // ===== ELEKTRONIK =====
            [
                'asset_code' => 'AST-001',
                'register_number' => 'REG-0001',
                'name' => 'Laptop Dell Latitude 5540',
                'category' => 'Elektronik',
                'quantity' => 15,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L005']->id,
                'description' => 'Laptop operasional staf sekretariat, spesifikasi i7-1355U/16GB/512GB',
            ],
            [
                'asset_code' => 'AST-002',
                'register_number' => 'REG-0002',
                'name' => 'PC Desktop Workstation',
                'category' => 'Elektronik',
                'quantity' => 8,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L008']->id,
                'description' => 'PC desktop untuk pengelola data dan IT support',
            ],
            [
                'asset_code' => 'AST-003',
                'register_number' => 'REG-0003',
                'name' => 'Printer Epson L15160',
                'category' => 'Elektronik',
                'quantity' => 3,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L005']->id,
                'description' => 'Printer A3+ multifungsi untuk cetak dokumen sekretariat',
            ],
            [
                'asset_code' => 'AST-004',
                'register_number' => 'REG-0004',
                'name' => 'Printer Epson L3210',
                'category' => 'Elektronik',
                'quantity' => 5,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L006']->id,
                'description' => 'Printer A4 untuk keperluan administrasi harian',
            ],
            [
                'asset_code' => 'AST-005',
                'register_number' => 'REG-0005',
                'name' => 'Scanner Fujitsu fi-7160',
                'category' => 'Elektronik',
                'quantity' => 2,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L004']->id,
                'description' => 'Scanner dokumen cepat untuk digitalisasi arsip sengketa',
            ],
            [
                'asset_code' => 'AST-006',
                'register_number' => 'REG-0006',
                'name' => 'Proyektor Epson EB-FH06',
                'category' => 'Elektronik',
                'quantity' => 4,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L001']->id,
                'description' => 'Proyektor untuk ruang sidang dan rapat',
            ],
            [
                'asset_code' => 'AST-007',
                'register_number' => 'REG-0007',
                'name' => 'TV LED Samsung 65"',
                'category' => 'Elektronik',
                'quantity' => 2,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L001']->id,
                'description' => 'TV layar besar untuk presentasi dan monitoring sidang',
            ],
            [
                'asset_code' => 'AST-008',
                'register_number' => 'REG-0008',
                'name' => 'AC Split Daikin 2 PK',
                'category' => 'Elektronik',
                'quantity' => 12,
                'unit' => 'Unit',
                'condition' => 'cukup',
                'location_id' => $loc['L005']->id,
                'description' => 'AC untuk ruang sekretariat dan administrasi',
            ],
            [
                'asset_code' => 'AST-009',
                'register_number' => 'REG-0009',
                'name' => 'AC Split Panasonic 1,5 PK',
                'category' => 'Elektronik',
                'quantity' => 8,
                'unit' => 'Unit',
                'condition' => 'rusak',
                'location_id' => $loc['L009']->id,
                'description' => 'AC ruang komisioner, beberapa perlu perbaikan',
            ],
            [
                'asset_code' => 'AST-010',
                'register_number' => 'REG-0010',
                'name' => 'UPS APC 1500VA',
                'category' => 'Elektronik',
                'quantity' => 6,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L008']->id,
                'description' => 'UPS untuk server dan perangkat IT',
            ],
            [
                'asset_code' => 'AST-011',
                'register_number' => 'REG-0011',
                'name' => 'Kamera DSLR Canon EOS 90D',
                'category' => 'Elektronik',
                'quantity' => 2,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L002']->id,
                'description' => 'Kamera untuk dokumentasi sidang dan kegiatan',
            ],
            [
                'asset_code' => 'AST-012',
                'register_number' => 'REG-0012',
                'name' => 'Sound System Wireless',
                'category' => 'Elektronik',
                'quantity' => 2,
                'unit' => 'Set',
                'condition' => 'baik',
                'location_id' => $loc['L001']->id,
                'description' => 'Sound system untuk ruang sidang utama',
            ],

            // ===== PERALATAN IT & JARINGAN =====
            [
                'asset_code' => 'AST-013',
                'register_number' => 'REG-0013',
                'name' => 'Server Dell PowerEdge R750',
                'category' => 'Peralatan IT',
                'quantity' => 2,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L008']->id,
                'description' => 'Server utama untuk aplikasi dan database',
            ],
            [
                'asset_code' => 'AST-014',
                'register_number' => 'REG-0014',
                'name' => 'NAS Synology DS1821+',
                'category' => 'Peralatan IT',
                'quantity' => 1,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L008']->id,
                'description' => 'Network Attached Storage untuk backup data',
            ],
            [
                'asset_code' => 'AST-015',
                'register_number' => 'REG-0015',
                'name' => 'Switch Cisco Catalyst 9200',
                'category' => 'Peralatan IT',
                'quantity' => 4,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L008']->id,
                'description' => 'Switch jaringan untuk distribusi koneksi LAN',
            ],
            [
                'asset_code' => 'AST-016',
                'register_number' => 'REG-0016',
                'name' => 'Access Point Ubiquiti U6 Pro',
                'category' => 'Peralatan IT',
                'quantity' => 10,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L008']->id,
                'description' => 'Access point WiFi 6 untuk coverage seluruh kantor',
            ],
            [
                'asset_code' => 'AST-017',
                'register_number' => 'REG-0017',
                'name' => 'Firewall Fortinet 60F',
                'category' => 'Peralatan IT',
                'quantity' => 1,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L008']->id,
                'description' => 'Firewall keamanan jaringan kantor',
            ],

            // ===== MEBEL =====
            [
                'asset_code' => 'AST-018',
                'register_number' => 'REG-0018',
                'name' => 'Meja Kerja Eksekutif',
                'category' => 'Mebel',
                'quantity' => 6,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L009']->id,
                'description' => 'Meja kerja untuk ruang komisioner dan pimpinan',
            ],
            [
                'asset_code' => 'AST-019',
                'register_number' => 'REG-0019',
                'name' => 'Meja Kerja Staf',
                'category' => 'Mebel',
                'quantity' => 25,
                'unit' => 'Unit',
                'condition' => 'cukup',
                'location_id' => $loc['L005']->id,
                'description' => 'Meja kerja standar untuk staf sekretariat',
            ],
            [
                'asset_code' => 'AST-020',
                'register_number' => 'REG-0020',
                'name' => 'Kursi Kantor Ergonomis',
                'category' => 'Mebel',
                'quantity' => 30,
                'unit' => 'Unit',
                'condition' => 'cukup',
                'location_id' => $loc['L005']->id,
                'description' => 'Kursi kantor dengan sandaran ergonomis',
            ],
            [
                'asset_code' => 'AST-021',
                'register_number' => 'REG-0021',
                'name' => 'Kursi Sidang Lipat',
                'category' => 'Mebel',
                'quantity' => 50,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L001']->id,
                'description' => 'Kursi untuk tamu sidang dan audiens',
            ],
            [
                'asset_code' => 'AST-022',
                'register_number' => 'REG-0022',
                'name' => 'Lemari Arsip Besi',
                'category' => 'Mebel',
                'quantity' => 10,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L004']->id,
                'description' => 'Lemari arsip sliding untuk dokumen sengketa',
            ],
            [
                'asset_code' => 'AST-023',
                'register_number' => 'REG-0023',
                'name' => 'Rak Buku Besar',
                'category' => 'Mebel',
                'quantity' => 6,
                'unit' => 'Unit',
                'condition' => 'cukup',
                'location_id' => $loc['L017']->id,
                'description' => 'Rak buku untuk perpustakaan dan pusat informasi',
            ],
            [
                'asset_code' => 'AST-024',
                'register_number' => 'REG-0024',
                'name' => 'Sofa Tamu 3-Seater',
                'category' => 'Mebel',
                'quantity' => 4,
                'unit' => 'Unit',
                'condition' => 'cukup',
                'location_id' => $loc['L003']->id,
                'description' => 'Sofa untuk area lobby dan ruang tunggu tamu',
            ],
            [
                'asset_code' => 'AST-025',
                'register_number' => 'REG-0025',
                'name' => 'Meja Rapat Bundar',
                'category' => 'Mebel',
                'quantity' => 3,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L014']->id,
                'description' => 'Meja rapat untuk ruang rapat pimpinan',
            ],
            [
                'asset_code' => 'AST-026',
                'register_number' => 'REG-0026',
                'name' => 'Lemari Display Trofi & Penghargaan',
                'category' => 'Mebel',
                'quantity' => 2,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L003']->id,
                'description' => 'Lemari kaca untuk display penghargaan institusi',
            ],

            // ===== KENDARAAN =====
            [
                'asset_code' => 'AST-027',
                'register_number' => 'REG-0027',
                'name' => 'Toyota Innova Zenix Hybrid',
                'category' => 'Kendaraan',
                'quantity' => 1,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L020']->id,
                'description' => 'Kendaraan dinas untuk ketua komisioner',
            ],
            [
                'asset_code' => 'AST-028',
                'register_number' => 'REG-0028',
                'name' => 'Toyota Kijang Innova',
                'category' => 'Kendaraan',
                'quantity' => 2,
                'unit' => 'Unit',
                'condition' => 'cukup',
                'location_id' => $loc['L020']->id,
                'description' => 'Kendaraan operasional untuk kegiatan lapangan',
            ],
            [
                'asset_code' => 'AST-029',
                'register_number' => 'REG-0029',
                'name' => 'Honda Vario 160',
                'category' => 'Kendaraan',
                'quantity' => 3,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L020']->id,
                'description' => 'Motor dinas untuk staf operasional lapangan',
            ],

            // ===== PERLENGKAPAN SIDANG & KEGIATAN =====
            [
                'asset_code' => 'AST-030',
                'register_number' => 'REG-0030',
                'name' => 'Wireless Microphone Set',
                'category' => 'Peralatan Sidang',
                'quantity' => 4,
                'unit' => 'Set',
                'condition' => 'baik',
                'location_id' => $loc['L001']->id,
                'description' => 'Mikrofon wireless untuk persidangan',
            ],
            [
                'asset_code' => 'AST-031',
                'register_number' => 'REG-0031',
                'name' => 'Recorder Digital Zoom H6',
                'category' => 'Peralatan Sidang',
                'quantity' => 2,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L002']->id,
                'description' => 'Audio recorder untuk dokumentasi sidang sengketa',
            ],
            [
                'asset_code' => 'AST-032',
                'register_number' => 'REG-0032',
                'name' => 'Tripod & Lighting Set',
                'category' => 'Peralatan Sidang',
                'quantity' => 3,
                'unit' => 'Set',
                'condition' => 'baik',
                'location_id' => $loc['L002']->id,
                'description' => 'Perlengkapan lighting untuk dokumentasi dan live streaming',
            ],

            // ===== PERLENGKAPAN IBADAH =====
            [
                'asset_code' => 'AST-033',
                'register_number' => 'REG-0033',
                'name' => 'Sajadah & Mukena Set',
                'category' => 'Perlengkapan Ibadah',
                'quantity' => 10,
                'unit' => 'Set',
                'condition' => 'baik',
                'location_id' => $loc['L018']->id,
                'description' => 'Perlengkapan ibadah untuk pegawai dan tamu',
            ],
            [
                'asset_code' => 'AST-034',
                'register_number' => 'REG-0034',
                'name' => 'Al-Quran & Kitab Suci',
                'category' => 'Perlengkapan Ibadah',
                'quantity' => 5,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L018']->id,
                'description' => 'Kitab suci untuk mushola kantor',
            ],

            // ===== PERLENGKAPAN DAPUR & PANTRY =====
            [
                'asset_code' => 'AST-035',
                'register_number' => 'REG-0035',
                'name' => 'Kulkas Sharp 2 Pintu',
                'category' => 'Perlengkapan Dapur',
                'quantity' => 2,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L019']->id,
                'description' => 'Kulkas untuk pantry dan ruang istirahat',
            ],
            [
                'asset_code' => 'AST-036',
                'register_number' => 'REG-0036',
                'name' => 'Dispenser Air Panas/Dingin',
                'category' => 'Perlengkapan Dapur',
                'quantity' => 4,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L019']->id,
                'description' => 'Dispenser air minum untuk setiap lantai',
            ],
            [
                'asset_code' => 'AST-037',
                'register_number' => 'REG-0037',
                'name' => 'Microwave Oven',
                'category' => 'Perlengkapan Dapur',
                'quantity' => 2,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L019']->id,
                'description' => 'Microwave untuk memanaskan makanan pegawai',
            ],
            [
                'asset_code' => 'AST-038',
                'register_number' => 'REG-0038',
                'name' => 'Coffee Maker Mesin Otomatis',
                'category' => 'Perlengkapan Dapur',
                'quantity' => 1,
                'unit' => 'Unit',
                'condition' => 'cukup',
                'location_id' => $loc['L019']->id,
                'description' => 'Mesin kopi otomatis untuk tamu dan rapat',
            ],

            // ===== PERLENGKAPAN KEBERSIHAN =====
            [
                'asset_code' => 'AST-039',
                'register_number' => 'REG-0039',
                'name' => 'Vacuum Cleaner',
                'category' => 'Perlengkapan Kebersihan',
                'quantity' => 3,
                'unit' => 'Unit',
                'condition' => 'baik',
                'location_id' => $loc['L015']->id,
                'description' => 'Vacuum cleaner untuk kebersihan ruangan',
            ],
            [
                'asset_code' => 'AST-040',
                'register_number' => 'REG-0040',
                'name' => 'Water Pump Gedung',
                'category' => 'Perlengkapan Kebersihan',
                'quantity' => 1,
                'unit' => 'Unit',
                'condition' => 'cukup',
                'location_id' => $loc['L015']->id,
                'description' => 'Pompa air untuk suplai air bersih gedung',
            ],
        ];

        foreach ($assets as $asset) {
            Asset::create($asset);
        }
    }
}
