services:
    laravel_app:
        image: 'localhost/simi-kiba-php-intl:8.4-fpm-nginx'
        container_name: simi_kiba_app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8000:8080'
        environment:
            AUTORUN_ENABLED: "false"
            DB_HOST: mysql
            REDIS_HOST: redis
        volumes:
            - '.:/var/www/html:z'
        networks:
            - simi_kiba_network
        depends_on:
            - mysql
            - redis

    mysql:
        image: 'docker.io/library/mysql:8.4'
        container_name: simi_kiba_mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-simi-kiba}'
            MYSQL_USER: '${DB_USERNAME:-sail}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'simi_kiba_mysql:/var/lib/mysql:z'
        networks:
            - simi_kiba_network

    redis:
        image: 'docker.io/library/redis:alpine'
        container_name: simi_kiba_redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'simi_kiba_redis:/data:z'
        networks:
            - simi_kiba_network

networks:
    simi_kiba_network:
        driver: bridge

volumes:
    simi_kiba_mysql:
        driver: local
    simi_kiba_redis:
        driver: local
